"""
SEAL — Sufficiency-Enforced Authorization Layer
=================================================
OmegaClaw Standalone | The Choke Valve

"No kinetic action executes without a SEAL."

The SEAL reads the Cryptographic Receipt generated by the Epistemic Compiler.
If Gate 5 (Sufficiency) didn't sign off, the SEAL physically cuts the wire.
"""

import hashlib
import json
import time
from dataclasses import dataclass


# ── Outcomes ──

AUTHORIZED = "AUTHORIZED"
DENIED = "DENIED"


@dataclass(frozen=True)
class SEALDecision:
    """Immutable authorization decision."""
    authorized: bool
    reason_code: str
    receipt_hash: str
    query_hash: str
    evidence_count: int
    gate5_satisfied: bool
    timestamp: float
    decision_hash: str = ""

    def __post_init__(self):
        if not self.decision_hash:
            payload = json.dumps({
                "a": self.authorized, "rc": self.reason_code,
                "rh": self.receipt_hash, "qh": self.query_hash,
                "ec": self.evidence_count, "g5": self.gate5_satisfied,
                "ts": self.timestamp,
            }, sort_keys=True)
            object.__setattr__(self, "decision_hash",
                               hashlib.sha256(payload.encode()).hexdigest())


class SEALViolation(Exception):
    """Raised when kinetic action is attempted without SEAL authorization."""
    def __init__(self, decision: SEALDecision):
        self.decision = decision
        super().__init__(
            f"SEAL DENIED: {decision.reason_code} "
            f"(receipt={decision.receipt_hash[:12]}, "
            f"evidence={decision.evidence_count})")


class SEAL:
    """Sufficiency-Enforced Authorization Layer.

    Reads the receipt from the Epistemic Compiler.
    If Gate 5 didn't satisfy, SEAL cuts the wire.
    """

    def __init__(self, min_evidence: int = 1,
                 require_gate5: bool = True,
                 require_sealed_receipt: bool = True):
        self._min_evidence = min_evidence
        self._require_gate5 = require_gate5
        self._require_sealed = require_sealed_receipt
        self._decisions: list = []

    def authorize(self, receipt) -> SEALDecision:
        """Read a receipt → produce authorization decision."""
        ts = time.time()
        receipt_hash = getattr(receipt, "receipt_hash", "")
        query_hash = getattr(receipt, "query_hash", "")
        outcome = getattr(receipt, "outcome", "")
        evidence_count = getattr(receipt, "evidence_count", 0)
        gate5_satisfied = self._check_gate5(receipt)

        if self._require_sealed and not receipt_hash:
            return self._deny("NO_RECEIPT", receipt_hash, query_hash,
                              evidence_count, gate5_satisfied, ts)

        if outcome != "CONTEXT_PRODUCED":
            return self._deny(f"OUTCOME_{outcome}", receipt_hash, query_hash,
                              evidence_count, gate5_satisfied, ts)

        if self._require_gate5 and not gate5_satisfied:
            return self._deny("GATE5_NOT_SATISFIED", receipt_hash, query_hash,
                              evidence_count, gate5_satisfied, ts)

        if evidence_count < self._min_evidence:
            return self._deny("INSUFFICIENT_EVIDENCE", receipt_hash, query_hash,
                              evidence_count, gate5_satisfied, ts)

        decision = SEALDecision(
            authorized=True, reason_code=AUTHORIZED,
            receipt_hash=receipt_hash, query_hash=query_hash,
            evidence_count=evidence_count, gate5_satisfied=gate5_satisfied,
            timestamp=ts)
        self._decisions.append(decision)
        return decision

    def enforce(self, receipt) -> SEALDecision:
        """Authorize + raise SEALViolation if denied."""
        decision = self.authorize(receipt)
        if not decision.authorized:
            raise SEALViolation(decision)
        return decision

    def verify(self, receipt, decision: SEALDecision) -> bool:
        """Replay: re-running authorize produces same result."""
        replayed = self.authorize(receipt)
        return replayed.authorized == decision.authorized

    @property
    def decisions(self) -> list:
        return list(self._decisions)

    def _check_gate5(self, receipt) -> bool:
        traces = getattr(receipt, "gate_traces", ())
        for trace in traces:
            gate_id = getattr(trace, "gate_id", -1)
            gate_name = getattr(trace, "gate_name", "")
            verdict = getattr(trace, "verdict", "")
            if gate_id == 5 or "SUFFICIENCY" in gate_name.upper():
                return verdict in ("PASS", "ELIMINATE")
        return False

    def _deny(self, reason, receipt_hash, query_hash,
              evidence_count, gate5, ts) -> SEALDecision:
        decision = SEALDecision(
            authorized=False, reason_code=reason,
            receipt_hash=receipt_hash, query_hash=query_hash,
            evidence_count=evidence_count, gate5_satisfied=gate5,
            timestamp=ts)
        self._decisions.append(decision)
        return decision
